### ISSUE TITLE
Unexpected jump in phase of HSExp pulses

### ISSUE THREAD

**Issue by schuenke** [kherz/pulseq-cest-library#11]
I just realized that there is an unexpected jump in the phase of the HSExp pulse(s). 

In https://github.com/kherz/pulseq-cest-library/blob/master/seq-library/DGErho_3T_001_4uT_adiaSL_DC100_120ms_braintumor/DGErho_3T_001_4uT_adiaSL_DC100_120ms_braintumor.seq in **line 23711** the value increases by 1 just to decrease bei 1 in **line 23712** again. 

![grafik](https://user-images.githubusercontent.com/37338697/115409241-dbb20780-a1f1-11eb-9d62-f655cb99f4be.png)

I guess this is not on purpose, is it? 

I checked the signal variable in Matlab before the block is added/the seq-file is written and that still looks fine to me. Thus, it might be a problem in pulseq itself?! 

In seq-files created with Python the jump doesn't exist.

**Comment by kherz** [comment]
The value in the .seq-file is not th ephase itself but the shape encoded with a run-length algorithm. Just checked the file, after decoding there is no phase jump in the signal. 
Still weird that it's different with pypulseq. Maybe the algorithms are not 100% the same, or different data types, etc...

**Comment by schuenke** [comment]
Yeah, I know its the compressed shape in the .seq file and ofc a phase step of 1 shouldn't be a problem since the phase is normalized to [0 1], but I just realized that for me the jump exists in the decompressed shape in MATLAB as well and it is the only remaining difference in the shape compression between MATLAB and Python.

In case we want to adjust it at some point: I could track it down to the **setBlock** function in **Sequence.m** where the phase is calculated using `phase = angle(event.signal);` and than wrapped to [0 2pi] using `phase(phase < 0) = phase(phase < 0) + 2*pi;`. 

If I change it to `phase(phase <= 0) = phase(phase <= 0) + 2*pi;` (**<=** instead of **<**), the jump in the decompressed phase is gone (didn't check it for all pulses yet), but pulseq and pypulseq still handle the compression a bit different 😃:

![grafik](https://user-images.githubusercontent.com/37338697/116091940-a1d77a00-a6a5-11eb-95ff-afcc2d651f40.png)
(This is from the HypSec pulse I used for the T1map file. **Left = python, right = MATLAB**)

**Comment by kherz** [comment]
Still, in pypulseq the phase normalization is the same (line 51 in block.py)
`phase[phase < 0] += 2 * np.pi`
So I assume the problem is somewhere deeper in the math libraries or in the compression function.
I would rather not change the normalization in the MATLAB code.

**Comment by schuenke** [comment]
I agree totally agree not to change the code at this point. Just thought it might be usefull to write it down here in case somebody else observes the same at some point. In this case its good to know that this phase jump between 0 and 1 (or rather 0 and 2pi) is not a big deal. It leads to some deviations between the .seq files created with MATLAB and python, but these deviations have no effect on the scanner/simulations.
