### ISSUE TITLE
Non-native YAML scalar data types in sim-library

### ISSUE THREAD

**Issue by lukas-k** [kherz/pulseq-cest-library#16]
Some of the simulation parameter YAML files contain pool fractions, relaxation rates, ... which are denoted as a fraction with numerator and denominator, for example in **GM_3T_001_bmsim.yaml**:

`
water_pool: {
  f: 1,
  r1: 1 / 1.3,
  r2: 1 / 75e-3
}`

Note that this notation (e.g. 1 / 1.3) is not a native YAML scalar data type and can not be interpreted by all YAML parsers correctly.

**Comment by kherz** [comment]
fixed with pr #20
