### ISSUE TITLE
ph weighted  seq

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest-library#17]
The ph weighted amine cest seq file does not run at our scanner.
No error idn logviewer.
Hybrid runs just without seq block.
Any ideas?

**Comment by kherz** [comment]
Sure it didn't run? The seq file in the library is a multi-slice protocol which has just 320 ms of saturation between ADCs. If you use that with the 3D readout it will just acquire the full volume after the short saturation.

**Comment by mzaiss** [comment]
True... Was just acoustic debugging.
For snapshot readout we probably have to run this to steady state. Wewill
check the data.

Kai Herz ***@***.***> schrieb am Mi., 28. Juli 2021, 12:48:
