### ISSUE TITLE
.sim to .yaml. or .sim.yaml  ? or BMsim.yaml ?

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest-library#2]
we changed the name to .sim fro simulation files
but i think yaml is actually cleaner, following Ptricks argumentation
still maybe something like  APT_001_brain.BMsim.yaml is best.

**Comment by kherz** [comment]
I wouldn't use uppercase in extensions, so .sim.yaml is probably best

**Comment by kherz** [comment]
@schuenke @KerstinHut , do you agree with .sim.yaml ?

**Comment by schuenke** [comment]
I actually think that the double extension leads to more confusion and mistakes than it helps. In my opinion a *.yaml file in a _sim-library_ subfolder is clear enough and the .yaml extension allows everbody to understand (or google) how to handle the file.

**Comment by mzaiss** [comment]
The problem is that it might not stay in this folder.
if people really try to pt it into their own pipeline and simulation with a completely dofferent structure they have some yaml files somewhere.  but we can agree to always put it in the file name 
right now we would have 
standard_cest_sim_params.yaml
if we always have a cest_sim in the name I am fine with .yaml

**Comment by schuenke** [comment]
Yeah, I would suggest a clear structure like
"CEST_sim_3T_brain_WM_<other infos!?>.yaml" etc

**Comment by kherz** [comment]
> 
> 
> Yeah, I would suggest a clear structure like
> "CEST_sim_3T_brain_WM_<other infos!?>.yaml" etc

We can make one CEST_sim_3T_brain_WM_Standard.yaml file and other files for the same modality, can be numbered, similar to the APT protocols, e.g. CEST_sim_3T_brain_WM_001.yaml, with a mandatory description indicating differences to the standard file in the header

**Comment by kherz** [comment]
And we can put a version attribute, e.g. "cest_sim_version : 1.0" in the file that is checked in the read function to ensure that the file is valid for the simulation and to have the possibility for backwards compatibily if we should need it at some point

**Comment by KerstinHut** [comment]
I totally agree with the CEST_sim-convention and .yaml-extension. The cest_sim_version might come in handy at some point.

**Comment by schuenke** [comment]
We decided to use the following notation:
**`<tissue>_<field strength>_<unique id>_bmsim.yaml`**
Examples would be: 
`GM_3T_001_bmsim.yaml`, `necrosis_3T_013_bmsim.yaml` or `calf-muscle_7T_003_bmsim.yaml`

If you agree, we can close this issue!?

**Comment by mzaiss** [comment]
I agree.
