### ISSUE TITLE
rf deadtime + rfRingdownTime  affect actual delay time

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest-library#35]
rf deadtime + rfRingdownTime as defined in the opts 

parser.addParamValue('rfDeadTime',0,@isnumeric);
parser.addParamValue('rfRingdownTime',0,@isnumeric);

will lead to slightly wrong timing of pulseq-CEST library sequences
I guess the td is efficiently too long, and delays need to be adjusted for rf deadtime + rfRingdownTime
might be the reasone for minimal differenes in BMSIM challenge
needs to be discussed, and might be different in pulseq 1.4

**Comment by kherz** [comment]
true, should be subtracted from interpulse delay for exact timing.

**Comment by mzaiss** [comment]
in the new pulseq-CEST master, a new case is given for simulations where both times can be set to zero.
we recommend this option for simulations as it is more comparable to other implemnetations.
