### ISSUE TITLE
M0 normalization now -300ppm or -1500 ?

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest-library#36]
i vote for -300 as it is tested

**Comment by schuenke** [comment]
maybe @kherz can enable GitHub discussions for this and the pulseq-cest repo to discuss questions like this!? It should be possible to create polls there, which would also be very convenient. 

Anyway, I also vote for -300 ppm.

**Comment by mzaiss** [comment]
ok, but add tag before and after
