### ISSUE TITLE
Include slices in seq-files

### ISSUE THREAD

**Issue by schuenke** [kherz/pulseq-cest-library#4]
In commit 80da70170e3451700e1eb670ec52a9049cfe5bee the number of slices was included in the seq-file and I was wondering if this is really a good idea. In my opinion, the pypulseq-cest seq-files should be independent of the MRI readout. However, if we include the number of slices and loop over them, the file can't be used with a single-shot 3D readout any more (or at least it doesn't make any sense !?). 

Therefore, I suggest that we provide/upload 'single slice' files only. 

Any opinions about that?

**Comment by kherz** [comment]
If the ADC is defined as a trigger to leave the pulseq-file and "acquire" a signal, I don't think that it is a problem to define multiple slices. If we have a sequence like here:  https://doi.org/10.1002/mrm.28516, there are even different saturation blocks between slices, which we could not define if we'd stick to 3D readouts. And a 3D compatible seq-file can always be produced by setting the number of slices to 1. So in terms of flexibility I would keep it that way.

**Comment by schuenke** [comment]
Okay, makes sense. I included the nSlices parameter (python intern its called n_slices) and prepared the pHw protocol with 25 slices.
