### ISSUE TITLE
Inconsistency in MultiPool_9p4T_001_multiB1sat_34Gauss_DC50_3p4s_brain

### ISSUE THREAD

**Issue by schuenke** [kherz/pulseq-cest-library#41]
I noticed the following inconsistencies in the **MultiPool_9p4T_001_multiB1sat_34Gauss_DC50_3p4s_brain** case.

I added a Python script that matches the current MATLAB implementation (60d58257bb9626fe9912cb8edbd065f3d8d8d053), but would ask @fglang and @mzaiss to double check the following points: 

- usually B0 ist defined and FREQ is calculated accordingly. In this case it is the other way around leading to slight deviations in the nominal B0
- a recover delay (trec = 3.5 s) is defined in the definitions but not added to the sequence. Is this on purpose or did you forget to add the delay? If it was on purpose, I suggest removing the delay from the definitions. 
- 4 B1 values are used, but only the last B1rms value is stored in the definitions. I suggest returning a list of B1rms values in the definitions (as implemented in the Python script)

**Comment by fglang** [comment]
Thanks, the missing Trec was indeed a bug. I now fixed it in the branch dev_fg and also added all B1rms values to the definitions.
Regarding B0: Currently it is defined as seq_defs.B0 = 9.4 in the Matlab script, and converted into frequencies using gyroRatio_hz  = 42.5764 as also defined in the script. Should we switch to a different convention with the frequency hard-coded in the definitions?

**Comment by schuenke** [comment]
Sorry, thought you were aware of the current PR of the dev_hack_feb_2023 branch (#40)

It would be great if you could adjust the protocol in the dev_hack_feb_2023 branch or merge your branch in to it. However, there are some deviations besides the points mentioned above. For example, you use the old B1cwpe naming.

**Comment by fglang** [comment]
No worries, I have just pushed the adjustments to the dev_hack_feb_2023 branch. Naming should now also be adjusted to B1rms.

**Comment by schuenke** [comment]
Thanks @fglang
I adjusted the python files (fc213323226ba1c86769657ca8d987c544d303aa) to match the updated Matlab files. The scripts yield identical seq-files now 👍
