### ISSUE TITLE
Inclusion of evaluation scripts 

### ISSUE THREAD

**Issue by schuenke** [kherz/pulseq-cest-library#50]
Recently (e.g., #48 #49) the discussion came up if evaluation scripts should be part of the pulseq-cest library or not.

In general, I like the idea of providing evaluation/post-processing scripts for the different CEST preparations, but I also see several arguments to keep these scripts outside the library or at least somehow separated from the seq-files. 

My biggest concern is that we won't be able to ensure that the provided scripts are actually in agreement with the (approved) seq-files of various publications that we provide. However, storing the seq-files and eval scripts in the same repository and even in the same sub-folder does suggest this imo. 

Another concern is that different evaluations (e.g. different metrics or different corrections) might be suitable for most of the seq-files. Actually, most of the CEST preparations can be evualted using a combination of the metrics MTRasym, MTRRex, AREX including or excluding B0/B1/motion correction etc. 

Thus, I would argue to provide different evaluation scripts/functions (that are ofc compatible with the standards defined in the pulseq-cest library) in a CEST toolbox, which again could be made available in Matlab and Python. Following the DRY principle, this would also avoid to repeat a lot of code in the different scripts (e.g. for the metrics and corrections). Providing the evaluation functionality within the (py)pulseq-cest and BMCTool repositories would be one option. Completely seperated repositories would be another one. 

We could still provide "eval_readme" files for every seq-library entry, where we list (a few) different post-processing steps that might be suitable for the preparation together with a disclaimer that these are just suggestions by the community, which are not necessarily in accordance with the evaluations actually used in the original publications. 

Happy to hear your opinions.

**Comment by mzaiss** [comment]
i think a minimal eval script that can solely be  evaluated with the
corresponding seqfile generated data would be great.

at least getting corrected Z and MTRasym.

of course many other evaluations are possible, but this can then be built
up from this minimalistic file

separate eval folder is possible, but this might lead to incompatibilities
of evals and seq data.







Patrick Schuenke ***@***.***> schrieb am Mi., 26. Juli 2023,
18:43:
