### ISSUE TITLE
APTw_3T_brain: Finding realistic in vivo simulation parameters

### ISSUE THREAD

**Issue by mzaiss** [kherz/pulseq-cest-library#7]
@ Kai, for GM you used specific CEST pool and relaxation parameters.
CEST pool came from van zijl et al.

where did GM water relaxation and MT come from?
Can you give the ressource for it and also add the WM_001 fiile according to the same ressource?

mybe we can mak an md file that lists ressource and respective T1, T2, MTC values at different field strengths.
Which values and from which pulicationn where teh vakues from your CETS conference abstract?

**Comment by kherz** [comment]
MT was also from that study (van Zijl et al.), but they had only GM values.
We could use Stanisz et al. (https://doi.org/10.1002/mrm.20605) for MT GM and WM.
And this ISMRM Abstract for Water T1 and T2 for all field strengths (https://pure.mpg.de/pubman/faces/ViewItemOverviewPage.jsp?itemId=item_2582024)
It's a little mixed then, but I think that's all good resources

**Comment by mzaiss** [comment]
@Kai: can you add the sources of the WM_001 parameters and some description why you chose it that way to the yaml comment section. similar as I did for the WM_002

**Comment by mzaiss** [comment]
![grafik](https://user-images.githubusercontent.com/8328474/119996858-6ba45780-bfcf-11eb-842d-76b7834b6e27.png)

I added WM_3T_002 and GLIO_3T_002 that match the publication of Heo et al (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4662920/figure/F2/) most closely, as can be seen above.

It is not perfect and open for discussion.

**Comment by mzaiss** [comment]
aded two more WM sims, 
Heo didnt provide NOE parameters though.
Liu was originally 7T.

WM_001 shows way to small CEST pools

heuritsic WM_002 still fits the data best

![WM_with_seq_APTw_3T_003](https://user-images.githubusercontent.com/8328474/120213766-e66dac80-c233-11eb-8a6c-57067ebcfc89.png)

**Comment by mzaiss** [comment]
An own 3T measurement (APTw_001) looks similar. peak around 2 ppm, then becomes negative after 4 ppm.
![grafik](https://user-images.githubusercontent.com/8328474/120224736-48361280-c244-11eb-90ef-e5d6f5a56898.png)

**Comment by kherz** [comment]
Probably best to not use wm_001 anymore, as it is clearly not as accurate as the newer ones. We can make a deprecated folder and put it there or remove it with the next merge, as it was never used in any publication anyways.

**Comment by mzaiss** [comment]
Well, we can just use the vanZijl one, that is most similar to WM_001.  And still a published reference interesting for comparison

**Comment by kherz** [comment]
But that's for GM. WM_001 is basically water and mt from WM_3T_Heo19.yaml but with cest pools from the vanZijl2018 paper. So it's not really an additional reference.

**Comment by mzaiss** [comment]
I see. Then lets make wm_002 to 001 
Or the default to 001?

**Comment by kherz** [comment]
closed with pr #19
